version: 2.1
jobs:
  build:
    docker:
      - image: cimg/openjdk:21.0.0
    steps:
      - checkout
      - run:
          name: Build with Gradle
          command: ./gradlew build
workflows:
  app:
    jobs:
      - build
