version: 2.1
jobs:
  build:
    docker:
      - image: cimg/openjdk:21.0.0
    steps:
      - checkout
      - run:
          name: Build
          command: ./gradlew build
  deploy:
    docker:
      - image: cimg/openjdk:21.0.0
    steps:
      - checkout
      - run:
          name: Deploy
          command: echo "Hello world"
workflows:
  build:
    jobs:
      - build
      - deploy:
          name: deploy-to-dev
          requires:
            - build
      - deploy:
          name: deploy-to-prod
          requires:
            - build
