version: 2.1
all-filter: &all-filter
  filters:
    branches:
      only: /.*/
    tags:
      only: /.*/
main-and-release-filter: &main-and-release-filter
  filters:
    branches:
      only: main
    tags:
      only: /.*/
release-filter: &release-filter
  filters:
    branches:
      ignore: /.*/
    tags:
      only: /.*/
orbs:
  aws-cli: circleci/aws-cli@4.1.2
  aws-ecr: circleci/aws-ecr@9.0.1
  terraform: circleci/terraform@3.2.1
jobs:
  build:
    docker:
      - image: cimg/openjdk:21.0.0
    steps:
      - checkout
      - run:
          name: Build with Gradle
          command: ./gradlew build
      - setup_remote_docker
      - aws-ecr/build_and_push_image:
          auth:
            - aws-cli/setup:
                region: us-east-1
          dockerfile: Dockerfile
          public_registry: true
          repo: app
          tag: $CIRCLE_SHA1
  deploy:
    docker:
      - image: cimg/base:2023.12
    parameters:
      terraform-workspace:
        type: string
    environment:
      AWS_REGION: eu-west-1
      TF_WORKSPACE: << parameters.terraform-workspace >>
    steps:
      - terraform/install:
          terraform_version: 1.6.5
      - run: echo "Deploying to $TF_WORKSPACE at $CONTEXT_ENVIRONMENT"
workflows:
  app:
    jobs:
      - build:
          <<: *all-filter
      - deploy:
          name: deploy-to-dev
          terraform-workspace: dev
          context: dev
          requires:
            - build
          <<: *main-and-release-filter
      - approve-to-prod:
          type: approval
          requires:
            - build
          <<: *release-filter
      - deploy:
          name: deploy-to-prod
          terraform-workspace: prod
          context: prod
          requires:
            - approve-to-prod
          <<: *release-filter
